on: [push]

jobs:

  Build:
    runs-on: ubuntu-latest
    name: A job to test the github action template

    steps:
      - name: oryks code coverage action
        id: selftest
        uses: twyle/github-action-template@v0.2.2
        with:
          myinput: lyle

      - name: action output
        run: |
          echo "${{ steps.selftest.outputs.myoutput }}"
